### PR TITLE
Clone "repo package" from ubuntu packages

### PR DESCRIPTION
**Pull request by karthikkm007**
Remove old system of cloning "repo" and update to this new system of installing "repo package" from ubuntu packages.

### CODE REVIEW

**Comment by adithya2306** [comment]
I track it directly from Google cause Ubuntu's one is often not updated

**Comment by karthikkm007** [comment]
ok

**Comment by mg712702** [comment]
Keks

**Comment by adithya2306** [comment]
keksi

**Comment by karthikkm007** [comment]
kool

**Pull request closed without merging**
